FROM golang:1.22 AS build

WORKDIR /app

COPY go.mod . 
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /allocator_service

FROM gcr.io/distroless/static:nonroot

COPY --from=build /allocator_service /allocator_service

EXPOSE 8080

USER nonroot

CMD ["/allocator_service"]
